### ISSUE TITLE
Tests fail since #99 was merged

### ISSUE THREAD

**Issue by Shimuuar** [nurpax/sqlite-simple#101]
There were tests which specifically tested conversion between text and number and now they fail

**Comment by jchia** [comment]
The failing asserts are from the 4 lines here:
https://github.com/nurpax/sqlite-simple/blob/91900808c0986f8a9f142c2897847a9d1e67d349/test/Errors.hs#L75

**Comment by jchia** [comment]
Fixed in b8a1f834.
