### ISSUE TITLE
Also return column names when executing a query

### ISSUE THREAD

**Issue by ad-si** [nurpax/sqlite-simple#104]
When I execute a query like `select * from users` it will return a `[[SQLData]]``, but I don't know the names of the columns.

This gets even more complicated with unusual queries like this:
```txt
sqlite> pragma schema_version;
┌────────────────┐
│ schema_version │
├────────────────┤
│ 42             │
└────────────────┘
sqlite> select 1,2,3;
┌───┬───┬───┐
│ 1 │ 2 │ 3 │
├───┼───┼───┤
│ 1 │ 2 │ 3 │
└───┴───┴───┘
```

Shouldn't there be a function which returns the results **and** the column names?

**Comment by jchia** [comment]
That is a question about the sqlite client. Do you have a related function from the sqlite C API that you would like to see sqlite-simple or direct-sqlite support for?

**Comment by jchia** [comment]
The sqlite client is not part of sqlite3-simple.

**Comment by ad-si** [comment]
For anyone arriving here with the same question:
There is the [`columnName`](https://github.com/IreneKnapp/direct-sqlite/blob/f4e73fe8d61117fef853697d0609c9efe888a3d8/Database/SQLite3/Direct.hs#L549) function to achieve exactly that!

```hs
withStatement conn "SELECT * FROM ps WHERE id=?" $ \stmt -> do
    colName <- columnName stmt 0
    colName @?= "id"
    colName2 <- columnName stmt 1
    colName2 @?= "t"
```
