### ISSUE TITLE
Add FromRow/ToRow instances for longer tuples?

### ISSUE THREAD

**Issue by eyeinsky** [nurpax/sqlite-simple#106]
Would the maintainers accept a PR to convert longer tuples to/from row? Something like: 
```haskell
instance (ToField a, ToField b, ToField c, ToField d, ToField e, ToField f,
          ToField g, ToField h, ToField i, ToField j, ToField k)
    => ToRow (a,b,c,d,e,f,g,h,i,j,k) where
    toRow (a,b,c,d,e,f,g,h,i,j,k) =
        [toField a, toField b, toField c, toField d, toField e, toField f,
         toField g, toField h, toField i, toField j, toField k]
```

And up to perhaps 20-member tuples?

**Comment by jchia** [comment]
Is (:.) not enough for your use case?

I have concerns about compilation speed, though I haven't profiled.

Or perhaps a flag can be used to enable the additional tuple instances so as to not affect the existing use cases.

Let's consider your use case first.

**Comment by eyeinsky** [comment]
Hi, sorry for taking so long :)

The use case I have is for very long rows, for which there are no ToRow instances defined.

I guess by `:.` you mean doing something like `toRow $ (a, b, c) :. (d, e, f)`, i.e splice the fields up into multiple tuples and use `:.` in between?

**Comment by jchia** [comment]
Yes.
