### ISSUE TITLE
New release with fixes?

### ISSUE THREAD

**Issue by goertzenator** [nurpax/sqlite-simple#108]
Any chance we can get some fixes merged into the release branch (which seems to be `ghc9`) along with a new hackage release?  I am specifically interested in 016f02bb88a5b06482b3246b3a2ec02ba13cf0e4 , but others might be useful too.

I was working on a new project with the latest sqlite-simple and was having troubles.  I discovered that the problem I was having was fixed and merged to master over 2 years ago but never made it to hackage.

Finally, package maintenance is often a thankless and unwanted responsibility.  I want to give a big thank you to those that are chipping away here and nudging it forward!

**Comment by jchia** [comment]
It seems that commit 016f02bb88a5b06482b3246b3a2ec02ba13cf0e4, from #99, introduced a test failure, at least on GHC 9.2.8:
```
cabal test -j10 --with-ghc=ghc-9.2.8                                                                                     ✘ 1   8s  00:48:43 
Build profile: -w ghc-9.2.8 -O1
In order, the following will be built (use -v for more details):
 - sqlite-simple-0.4.18.1 (test:test) (first run)
Preprocessing test suite 'test' for sqlite-simple-0.4.18.1..
Building test suite 'test' for sqlite-simple-0.4.18.1..
Running 1 test suites...
Test suite test: RUNNING...
### Failure in: 24:Errors                   
test/Errors.hs:33
assertResultError exc
Cases: 47  Tried: 47  Errors: 0  Failures: 1

Test suite test: FAIL
Test suite logged to:
/home/jchia/gh/sqlite-simple/dist-newstyle/build/x86_64-linux/ghc-9.2.8/sqlite-simple-0.4.18.1/t/test/test/sqlite-simple-0.4.18.1-test.log
0 of 1 test suites (0 of 1 test cases) passed.
Error: cabal: Tests failed for test:test from sqlite-simple-0.4.18.1.
```

Any ideas?

**Comment by goertzenator** [comment]
Ah, thank you for the explanation.  I will work on the PR to fix that.

**Comment by goertzenator** [comment]
As per comments in PR #99, I would like to retract that PR.  Closing this issue.
