### ISSUE TITLE
Question:Is it possible to enable `executeNamed` for handling excess parameters?

### ISSUE THREAD

**Issue by WendaoLee** [nurpax/sqlite-simple#109]
I'm dealing with a complex data structure which contains many user-defined types,like:
```haskell
-- some code has been ignored
data TopicMetaData = TopicMetaData{
  topicTag::[TopicTag],
  topicCommentsCount::Int,
  topicRelatedGroup::GroupMetaData
}deriving(Generic,Show)

data GroupMetaData = GroupMetaData{
  groupDomain::Text,
  owner::Maybe Author,
  topicTagsNormal::[TopicTag]
}deriving(Generic,Show)

..
```
I'm trying to wirte functions like this:
```haskell
parseGroupMetaData :: GroupMetaData -> [NamedParam]
parseGroupMetaData the_data =
  let directly_parsed =
        [ ":groupDomain" := groupDomain the_data
        , ":memberRole" := memberRole the_data
        , ":managerName" := managerName the_data
        ]
      owner_data = fromMaybe defaultAuthor (owner the_data)
  in directly_parsed ++ parseAuthorData owner_data
```
So I can just use one parse function to get all namedparams,and deal with different tables like: 
```haskell
-- | RecordMetaData
insertRecordTable :: Connection -> [NamedParam] -> IO ()
insertRecordTable con = executeNamed con recordInsertSql

-- | MetaData.GroupSnapshot
insertGroupSnapshot :: Connection -> [NamedParam] -> IO ()
insertGroupSnapshot con = executeNamed con groupSnapshotInsertSql
```
But I got error:
```log
*** Exception: FormatError {fmtMessage = "SQL query contains 26 params, but 36 arguments given", fmtQuery = "INSERT OR IGNORE INTO GroupSnapshot (    rc_time,    group_domain,    group_create_time,    group_id,    group_type,    group_owner_id,    group_url,    group_name,    group_avatar_url,    group_mask_color,    member_nums,    member_role,    member_name,    manager_name,    topic_nums,    is_enable_subscribe,    is_enable_reply_comment,    is_allow_downvote_topic,    is_allow_downvote_comment,    is_allow_binding_video,    can_create_topic_event,    can_preview_collection_photos,    is_subject_group,    can_set_collection_photos,    join_type,    club_id ) VALUES (   :recordTime,   :groupDomain,   :groupCreateTime,   :groupId,   :groupType,   :groupOwnerId,   :groupUrl,   :groupName,   :groupAvatarUrl,   :groupMaskColor,   :memberNums,   :memberRole,   :memberName,   :managerName,   :topicTotalNums,   :enableSubscribe,   :isEnableReplyComment,   :allowDownvoteTopic,   :allowDownvoteComment,   :allowBindingVideo,   :canCreateTopicEvent,   :previewCollectionPhotos,   :isSubjectGroup,   :canSetCollectionPhotos,   :joinType,   :clubId );", fmtParams = ["(\":recordTime\",SQLInteger 1702383113)","(\":groupDomain\"
```
Then I wonder if it is possible to enable `executeNamed` handling excess parameters.🤔Is it possible to be a new feature?Or any advice for my case?I'd appreciate if someone could give me any suggestion.🥰

**Comment by jchia** [comment]
I can't tell what you are trying to achieve. recordInsertSql & groupSnapshotInsertSql are not given. IDK what insertRecordTable & insertGroupSnapshot are supposed to do, or how they relate to TopicMetaData or GroupMetaData.

I also don't know how you called the functions to get that error message.

Could this perhaps actually be a Haskell question instead of a sqlite-simple question?

**Comment by WendaoLee** [comment]
> I can't tell what you are trying to achieve. recordInsertSql & groupSnapshotInsertSql are not given. IDK what insertRecordTable & insertGroupSnapshot are supposed to do, or how they relate to TopicMetaData or GroupMetaData.
> 
> I also don't know how you called the functions to get that error message.
> 
> Could this perhaps actually be a Haskell question or program design question instead of a sqlite-simple question?

Ah,sorry for misunderstanding.For a short,my question is:Is it possible for `sqlite-simple`'s [executeNamed](https://hackage.haskell.org/package/sqlite-simple-0.4.18.2/docs/Database-SQLite-Simple.html#v:executeNamed) supporting handling excess named-parameters?

For a brief instance:
```haskell

insertSql = "INSERT INTO one_table(primary_key,other_column) VALUES (:primaryValue,:thisTablesColumnValue)"

-- executeNamed :: Connection -> Query -> [NamedParam] -> IO ()

executeInsertWithExcessNamedParameters con = executeNamed con insertSql [":primaryValue" := 0,":thisTablesColumnValue" := "bar",":otherTableColumnValue" := "foo"]
```
But when excute this,it will throw error:
```log
*** Exception: FormatError {
fmtMessage = "SQL query contains 2 params, but 3 arguments given", 
fmtQuery = "INSERT INTO one_table(primary_key,others) VALUES (:primaryValue,:thisTablesColumnValue)", 
fmtParams = ["(\":primaryValue\",SQLInteger 0)","(\":thisTablesColumnValue\",SQLText \"bar\")","(\":otherTableColumnValue\",SQLText \"foo\")"]}
```
It seems like `executeNamed` just construct the params into the query,without taking values from `[NamedParam]` selectively.

So is it possible to make `executeNamed` has a step to  selectively bind the value from `[NamedParam]` into the query?For the benefits,it will enable user to convert value with just one parser function if the origin data contains other tables' value.e.g.

```haskell
data Foo = {
 oneTablePrimaryKeyValue::Int,
 oneTableOtherColumnValue::Text,
 otherTableValue::Text
}

-- just one function to get all params which storage need
parseFoo::Foo -> [NamedParam]

insertOtherTableSql = "INSERT INTO other_table(this_table_column) VALUES (:otherTableColumnValue)"
insertThisTableSql = "INSERT INTO one_table(primary_key,other_column) VALUES (:primaryValue,:thisTablesColumnValue)"


generalInsert foo conn = do
  let allValues = parseFoo foo
  executeNamed conn insertThisTableSql allValues
  executeNamed conn insertOtherTableSql allValues
```

Do hope I have clarified my thoughs.Apology for my previous confused declaration which waste your time.I'm really sorry.

**Comment by jchia** [comment]
In understand your issue now.

Do you think that `bindParameterCount` and `bindParameterName` can be used to filter out unused parameters to address your issue?

**Comment by WendaoLee** [comment]
> In understand your issue now.
> 
> Do you think that `bindParameterCount` and `bindParameterName` can be used to filter out unused parameters to address your issue?

Well,sorry for my limited knowledge and understanding.Could you give me any reference for that?For I haven't found theses in the documents.Thanks for your valuable time.🥰

**Comment by WendaoLee** [comment]
> You could search the documentation for the 2 functions I named on stackage:
> https://www.stackage.org/nightly-2023-12-11/package/direct-sqlite-2.3.28

Thanks for your help！😘

**Comment by WendaoLee** [comment]
Here's my solution:

First,install `direct-sqlite` which is the build-depends of `sqlite-simple`.We need low-level api to deal with `Statement`

```haskell
import qualified Database.SQLite3 as LowLevel


metadata_conn <- open "./metadata.db"

-- define in <https://hackage.haskell.org/package/sqlite-simple-0.4.18.2/docs/Database-SQLite-Simple.html#t:Connection>
-- use this to deal with low-level api encapsulated in `direct-sqlite`
let meta_conn_handler = connectionHandle metadata_conn
-- get `Statement` from your sql
stm <- LowLevel.prepare meta_conn_handler (fromQuery recordInsertSql)
-- get the nums of your sql's binded parameters
count <- LowLevel.bindParameterCount stm
```

Then write some util functions:

```haskell
getParametersBindIndexs::ParamIndex -> [ParamIndex]
getParametersBindIndexs large_index = [LowLevel.ParamIndex 1 .. large_index]


getBindedParameterNames :: LowLevel.Statement -> [ParamIndex] -> IO [Text]
getBindedParameterNames stm indexs = do
  monads <- mapM (bindParameterName stm) indexs
  return (map (fromMaybe "") monads)

-- So I can use this to filter [NamedParam]
filterNamedParams :: [Text] -> [NamedParam] -> [NamedParam]
filterNamedParams bind_names = filter (\x -> getKey x `elem` bind_names)
```

For the above `getKey` is the extended Class I defined:

```haskell
class NamedParamToTuple a where
  toTuple::a->(Text,SQLData)
  toNamedParam::(Text,SQLData) -> a
  isKey:: a -> Text -> Bool
  getKey::a -> Text

instance NamedParamToTuple NamedParam where
  toTuple (k:=v) = (k,toField v)
  toNamedParam (k,v) = k := v
  isKey a z = fst (toTuple a) == z
  getKey (k:=v) = k
```

Do hope this issue will help someone in the future days.

**Comment by WendaoLee** [comment]
Well,I think maybe we can add a function like `executeNamedFiltered` into the lib?

**Comment by jchia** [comment]
Making a name-filtered variant of only `executeNamed` is too adhoc. There is also `queryNamed`. At the base there is `bindName`. I haven't checked what other functions could be related to the name filtering. I also have to think of other implications and any problems with filtering parameters.

**Comment by WendaoLee** [comment]
> Making a name-filtered variant of only `executeNamed` is too adhoc. There is also `queryNamed`. At the base there is `bindName`. I haven't checked what other functions could be related to the name filtering. I also have to think of other implications and any problems with filtering parameters.

Could you please offer some examples illustrating the implications and potential issues associated with this?If you have time.👀Thanks.😽

**Comment by WendaoLee** [comment]
> > Making a name-filtered variant of only `executeNamed` is too adhoc. There is also `queryNamed`. At the base there is `bindName`. I haven't checked what other functions could be related to the name filtering. I also have to think of other implications and any problems with filtering parameters.
> 
> Could you please offer some examples illustrating the implications and potential issues associated with this?If you have time.👀Thanks.😽

In my immature thoughts,it seems that we can just use the low-level api in `direct-sql` to write some filter function,as the `sqlite-simple` depends on it.

**Comment by jchia** [comment]
I'm not mainly talking about how to implement the feature using direct-sqlite. I'm talking about the proper interface design for the new feature.

If there is a name-filtering variant of `executeNamed` there should be one also for `queryNamed`. Having just one of them would be poor design.

They can be based on a name-filtering variant of `withStatementNamedParams`, which can use `bindParameterCount` and `bindParameterName` from direct-sqlite to do the filtering.

And of course, there should be new tests for the new feature.

**Comment by WendaoLee** [comment]
> I'm not mainly talking about how to implement the feature using direct-sqlite. I'm talking about the proper interface design for the new feature.
> 
> If there is a name-filtering variant of `executeNamed` there should be one also for `queryNamed`. Having just one of them would be poor design.
> 
> They can be based on a name-filtering variant of `withStatementNamedParams`, which can use `bindParameterCount` and `bindParameterName` from direct-sqlite to do the filtering.
> 
> And of course, there should be new tests for the new feature.

Ah,I'm sorry I'm not get your main idea before.Now I know what you mean.Thanks for your reply.
