### ISSUE TITLE
add queryWith and queryWith_ helper functions

### ISSUE THREAD

**Issue by nurpax** [nurpax/sqlite-simple#34]
postgresql-simple has a couple of additional query functions:

```
-- | A version of 'query' taking parser as argument
queryWith :: ToRow q => RowParser r -> Connection -> Query -> q -> IO [r]

-- | A version of 'query_' taking parser as argument
queryWith_ :: RowParser r -> Connection -> Query -> IO [r]
```

These seem helpful, so filing this bug to consider some day adding these into sqlite-simple.

**Comment by nurpax** [comment]
queryWith_ was added in https://github.com/nurpax/sqlite-simple/pull/43.  Should probably extend to queryWith too.

**Comment by supki** [comment]
Hey, is there any ETA on adding this?

**Comment by nurpax** [comment]
@supki No ETA really, but I'd be happy to look at a pull request for this.  queryWith_ is already in v0.4.9, so only queryWith is missing.

**Comment by nurpax** [comment]
It was easy enough to implement so I went ahead and added it.  Will be on Hackage shortly as v0.4.12.0.

**Comment by supki** [comment]
Thanks!
