### ISSUE TITLE
Add possibility to dynamically choose the table for a query

### ISSUE THREAD

**Issue by howabouthis** [nurpax/sqlite-simple#80]
As far as I know, there's currently no way to build a query where the value of the FROM clause is a variable. To my understanding, the library relies on the parametered query capabilities of SQLite itself, and SQLite doesn't offer this functionality either.

The problem is that this library strictly forbids building queries by concatenating strings, which is normally a possible way to solve this problem.

**Comment by sigrlami** [comment]
@howabouthis can you show an example even in pseudocode?

**Comment by howabouthis** [comment]
> You can definitely construct your own query strings dynamically. Just need to use the `Query` constructor to wrap your strings.
> 
> For example, here's a snippet from one of the unit tests (https://github.com/nurpax/sqlite-simple/blob/master/test/Simple.hs):
> 
> ```
> testSimpleTimeFract :: TestEnv -> Test
> testSimpleTimeFract TestEnv{..} = TestCase $ do
>   let timestr = "2012-08-17 08:00:03.256887"
>       time    = read timestr :: UTCTime
>   -- Try inserting timestamp directly as a string
>   execute_ conn "CREATE TABLE timefract (t TIMESTAMP)"
>   execute_ conn (Query (T.concat ["INSERT INTO timefract (t) VALUES ('", T.pack timestr, "')"]))
>   [Only t] <- query_ conn "SELECT * FROM timefract" :: IO [Only UTCTime]
>   assertEqual "UTCTime" time t
>   rows <- query conn "SELECT * FROM timefract WHERE t = ?" (Only time) :: IO [Only UTCTime]
>   assertEqual "should see one row result" 1 (length rows)
> ```

Correct me if I'm wrong, but in the example the table name is statically defined to be "timefract". 

I'm trying to have a dynamically changing table name. A simple example of this would be loading data from a table with the name given as a parameter to the program. In my use case the data held in each table is of the same type and format, so I don't need to know which table I'm actually accessing.

So I'd like to do something like this:
`r <- query_ conn ("SELECT * FROM " ++ "table_name") :: IO [(Int, ByteString)]`

**Comment by nurpax** [comment]
> Correct me if I'm wrong, but in the example the table name is statically defined to be "timefract".

This line is not:

```
  execute_ conn (Query (T.concat ["INSERT INTO timefract (t) VALUES ('", T.pack timestr, "')"]))
```

So something like this should work:

```
import qualified Data.Text as T
r <- query_ conn (Query (T.concat ["SELECT * FROM ", "table_name"])) :: IO [(Int, ByteString)]
```

(Note that query string doesn't use the `String` type but `Text`)

The Query newtype pattern was originally borrowed from `mysql-simple` and `postgresql-simple` -- these libraries use the exact same type.

**Comment by howabouthis** [comment]
Oh, that works. Thank you!
