### ISSUE TITLE
Hackage release does not match repository

### ISSUE THREAD

**Issue by fosskers** [nurpax/sqlite-simple#84]
Hi there, [the recent Hackage release](http://hackage.haskell.org/package/sqlite-simple-0.4.17.0/sqlite-simple.cabal) of version `0.4.17.0` does not seem to match what is in this repo, in particular with respect to the bounds for `semigroups` as updated [in this PR](https://github.com/nurpax/sqlite-simple/pull/83/files#diff-07a0b81e86c348bcc1481a911cea0b60). Something may have gone wrong during the release process.

**Comment by nurpax** [comment]
@sigrlami I wonder if the cabal file’s been edited out of repo in hackage and the changes not brought back to github?

**Comment by sigrlami** [comment]
@fosskers @nurpax I'll investigate that

**Comment by sigrlami** [comment]
@fosskers local merge went wrong without any indication. I'll have to re-upload the package with updated bounds, so it will be 0.4.18.0.

**Comment by exaexa** [comment]
Is it possible that this also affects other files?

In particular, build of 0.4.17.0 from hackage on ghc 8.8.x seems to be failing because of `fail` being defined in Monad and not in MonadFail, which is in fact fixed in git for quite a long time now.

The error:
```
Preprocessing library for sqlite-simple-0.4.17.0..
Building library for sqlite-simple-0.4.17.0..
[ 1 of 12] Compiling Database.SQLite.Simple.Ok ( Database/SQLite/Simple/Ok.hs, dist/build/Database/SQLite/Simple/Ok.o )

Database/SQLite/Simple/Ok.hs:75:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
   |
75 |     fail str = Errors [SomeException (ErrorCall str)]
   |     ^^^^
```

Thanks!

**Comment by fosskers** [comment]
My last PR was supposed to have fixed all that.

**Comment by sigrlami** [comment]
It's my fault introducing error on silent merge last week. 
1) Repo reverted to correct version. 
2) version 0.4.17.0 is deprecated
3) new version 0.4.18.0 uploaded and tested with lts-15.1, 15.2 with 8.8.x additionally.

@fosskers @exaexa please verify it's working for you. Extra deps required for `stack.yaml`

```
extra-deps:
- sqlite-simple-0.4.18.0@sha256:3ceea56375c0a3590c814e411a4eb86943f8d31b93b110ca159c90689b6b39e5,3002
- direct-sqlite-2.3.26@sha256:04e835402f1508abca383182023e4e2b9b86297b8533afbd4e57d1a5652e0c23,3718
```

**Comment by fosskers** [comment]
Thank you kindly, I'll get this confirmed on Monday!

**Comment by fosskers** [comment]
Yup, looks good! Thank you.

**Comment by exaexa** [comment]
Confirming, 0.4.18.0 works perfectly.

Thanks!
