### ISSUE TITLE
`fold_` in parallel

### ISSUE THREAD

**Issue by erictapen** [nurpax/sqlite-simple#93]
What would be a good way to run expensive computations in a `fold_` in parallel? So we can process multiple rows at once, but still run in constant time?

```
fold_ :: FromRow row => Connection -> Query -> a -> (a -> row -> IO a) -> IO a
```

If we assume `Semigroup a => a`, this should be possible, but I don't know how to express it in ideomatic Haskell.

**Comment by jchia** [comment]
I don't understand the question. Is it a question about Haskell or question about the library? Do you have a concrete code example using sqlite-simple illustrating the problem you are trying to solve?

**Comment by erictapen** [comment]
I'm afraid I won't be able to dig up the problem I had then. I'll close this then.
