### ISSUE TITLE
Is this repository still active?

### ISSUE THREAD

**Issue by danwdart** [nurpax/sqlite-simple#97]
I notice a whole lot of reasonable looking pull requests, some of which haven't been commented on, and wondering if the repo is still alive.

If it is, hello, please let me know.

If it isn't, then I could take it over if people want.

**Comment by goertzenator** [comment]
I think this package is important and would love to see it maintained a little more than it currently is.

**Comment by danwdart** [comment]
I have asked @nurpax on email if they are still interested, or would like me to do it.

**Comment by kmicklas** [comment]
Any update on this? I think this is an important package in the Haskell ecosystem and it would be great to have active maintenance.

**Comment by danwdart** [comment]
@sigrlami has explained that they are still interested and has a release schedule:

https://github.com/nurpax/sqlite-simple/issues/95#issuecomment-890938785

**Comment by jchia** [comment]
@danwdart That was almost a year ago with no updates since.

**Comment by danwdart** [comment]
Yeah, true, well I don't mind if you want to take it over or taking it over myself.

**Comment by danwdart** [comment]
I think I'd better find another way to email first.

**Comment by jchia** [comment]
This repo is currently active. I am maintaining it and one of the maintainers listed on Hackage. It will take time and effort to go through the old issues and PRs that predate my involvement, though, since I am not necessarily familiar with the context.

Contacting @sigrlami by email has yielded no response, but he is active in other github repos, so I assume he has lost interest.

**Comment by nurpax** [comment]
Hi @jchia!   Original author of sqlite-simple here.  I'm happy to see an active maintainer picking up this library.  I lurk in the comments but my only input to this library for a long time has been repeating [this comment](https://github.com/nurpax/sqlite-simple/issues/91#issuecomment-813673032) to advice against parsing input SQL strings and letting native SQLite do the parsing. :)
